@extends('layouts.main')
@section('profile')
  <profile-component></profile-component>
@endsection
@section('skills')
  <skills-component></skills-component>
@endsection
@section('jobs')
  <jobs-component></jobs-component>
@endsection
